name: Training Otomatis

on: [push]

jobs:
  run-training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # GABUNGAN INSTALL & RUN (Dengan Fix Token)
      - name: Install and Run Project
        env:
          # Variabel MLflow standar
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          # --- KUNCI PERBAIKAN ---
          # Kita masukkan password sebagai Token agar dagshub.init tidak minta login browser
          DAGSHUB_TOKEN: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          echo "Sedang menginstall library..."
          pip install pandas scikit-learn mlflow dagshub
          
          echo "Sedang menjalankan script..."
          cd Membangun_model
          python modelling.py
